export const CLEAR_ALL = 'CLEAR_ALL'
export const LOAD_CREDIT_DATA = "LOAD_CREDIT_DATA"
export const LOADING_CREDIT_DATA = "LOADING_CREDIT_DATA"
export const LOADING_STOCK_DATA = "LOADING_STOCK_DATA"
export const LOAD_STOCK_DATA = "LOAD_STOCK_DATA"
export const GET_CURRENT_FILTER_CREDIT_DATA = "GET_CURRENT_FILTER_CREDIT_DATA"
export const GET_CURRENT_FILTER_STOCK_DATA = "GET_CURRENT_FILTER_STOCK_DATA"